FROM	alpine:latest

#Still what about no cache
RUN		apk update  && apk upgrade
RUN		apk add mariadb openrc

COPY	tools/setup_db.sql	.
COPY	tools/test.sh	.

RUN 	chmod +x test.sh

CMD [ "./test.sh" ]

ENTRYPOINT	["mysqld", "--bind-address=0.0.0.0"]

#https://wiki.alpinelinux.org/wiki/MariaDB
#RUN	apk add mysql mysql-client

#RUN		mariadb-install-db --datadir=/var/lib/mysql \
#			--auth-root-authentication-method=normal
#RUN 	mysql_install_db
#RUN 	/usr/share/mariadb/mysql.server start
#RUN		chown -R mysql:mysql /var/lib/mysql 

#COPY ./tools /var/www/

#RUN chmod 755 /var/lib/mysql

#RUN service mysql start 
#&& mysql < /var/www/initial_db.sql && rm -f /var/www/steup_db.sql;

#RUN	sed -i "s/bind-address/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf

#is that necessary ?
EXPOSE 3306